using System;
using System.Globalization;
using System.Windows;
using System.Windows.Input;
using PassWinmenu.Configuration;

namespace PassWinmenu.Windows
{
	internal sealed partial class PasswordWindow
	{
		private readonly PasswordGenerationConfig passwordGenerationConfig;

		public PasswordWindow(string filename, PasswordGenerationConfig passwordGenerationConfig)
		{
			this.passwordGenerationConfig = passwordGenerationConfig;
			WindowStartupLocation = WindowStartupLocation.CenterScreen;
			InitializeComponent();

			Title = "Add new password";

			Generator.Initialize(passwordGenerationConfig);
			AddDefaultMetadata(filename);
			Generator.FocusPassword();
		}

		/// <summary>The password chosen/generated by the user.</summary>
		public string GeneratedPassword => Generator.GeneratedPassword;

		private void AddDefaultMetadata(string filename)
		{
			var now = DateTime.Now;
			var extraContent = passwordGenerationConfig.DefaultContent
				.Replace("$filename", filename)
				.Replace("$date", now.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture))
				.Replace("$time", now.ToString("HH:mm:ss", CultureInfo.InvariantCulture));
			ExtraContent.Text = extraContent;
		}

		private void Btn_OK_Click(object sender, RoutedEventArgs e)
		{
			DialogResult = true;
			Close();
		}

		private void Btn_Cancel_Click(object sender, RoutedEventArgs e)
		{
			DialogResult = false;
			Close();
		}

		private void Window_KeyUp(object sender, KeyEventArgs e)
		{
			if (e.Key == Key.Escape)
			{
				DialogResult = false;
				Close();
			}
		}
	}
}
